version = 0.1
[default.deploy.parameters]
stack_name = "third-kinesis"
resolve_s3 = true
s3_prefix = "third-kinesis"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "KinesisStreamName=\"third-kn-data\""
image_repositories = []
